### ISSUE TITLE
The thread tried to read from or write to a virtual address for which it does not have the appropriate access

### ISSUE THREAD

**Issue by isaac2004** [Microsoft/code-challenges#24]
I am trying to open a Snapshot that I am logging in Azure in Visual Studio 15.5 and I get the following error

>The thread tried to read from or write to a virtual address for which it does not have the appropriate access

If I attempt to debug with managed code, I get this exception

> Unhandled exception at 0x0C492A36 in 8acbe77983bb43b4bad3ef7f2224a765.dmp: 0xC0000005: Access violation reading location 0x00000004.

I have tried running VS as Admin but this isn't resolved. Is it a symbol loading issue? Not sure how to debug this

**Comment by straightcurve** [comment]
So did you figure it out?

**Comment by isaac2004** [comment]
@straightcurve this is the functionality you get with Null Reference on Release Build. That is as far as I went.
